theme = "monkeyBooks"
baseURL = "https://ram535.github.io/website/"
publishDir = "docs"
languageCode = "en-us"
title = "ram535.github.io"
MetaDataFormat = "toml"

[[menu.main]]
    name = "Blog"
    url = "/"
[[menu.main]]
    name = "Dartlang"
    url = "/dartlang"

